[package]
name = "passman"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
rand = "0.9.2"
tabled = "0.20.0"
arboard = "3.6.1"
